### ISSUE TITLE
meta: docs issue tracker

### ISSUE THREAD

**Issue by saihaj** [graphql/graphql-js#3150]
Track all docs related issues for GraphQL.JS open in [`graphql/graphql-js`](https://github.com/graphql/graphql-js), [`graphql/graphql.github.io`](https://github.com/graphql/graphql.github.io).

- [ ] #433
- [ ] #1368 
- [ ] #2098 
- [ ] #2206 
- [ ] #2244
- [ ] #2567
- [ ] #2941 
- [ ] #2950 
- [ ] https://github.com/graphql/graphql.github.io/issues/119
- [ ] https://github.com/graphql/graphql.github.io/issues/163
- [ ] https://github.com/graphql/graphql.github.io/issues/252
- [ ] https://github.com/graphql/graphql.github.io/pull/683
- [ ] https://github.com/graphql/graphql.github.io/issues/669
- [ ] https://github.com/graphql/graphql.github.io/issues/1049
- [ ] https://github.com/graphql/graphql.github.io/pull/1051
- [ ] https://github.com/graphql/graphql-js-wg/issues/3

**Comment by saihaj** [comment]
Started the site here https://github.com/graphql/graphql-js/pull/3269

**Comment by kasir-barati** [comment]
Hi @saihaj, Just wondering if we could use ES6 syntax at least if we ain't aiming for TS. I am talking about examples that we have here: https://graphql-js.vercel.app/tutorials/running-an-express-graphql-server

I just think that this much work is being poured into this. So let's do a modernization too, like what is going on here: https://github.com/graphql/graphql.github.io/issues/1821

Any comment?

**Comment by yaacovCR** [comment]
we now have a script and lint rules for automatically generating API docs for v16 and v17 from source, and our documentation has been refreshed by many valuable contributors.
