### ISSUE TITLE
v17 Roadmap

### ISSUE THREAD

**Issue by yaacovCR** [graphql/graphql-js#4205]
Some initial thoughts for PRs to consider for v17 are below. Please add comments for discussion! What would you like to see in v17?

Additional Type or Otherwise Breaking Changes:

- [ ] https://github.com/graphql/graphql-js/pull/3511
- [ ] https://github.com/graphql/graphql-js/pull/2181

Multiple Packages:

- [ ] https://github.com/graphql/graphql-js/pull/4188
- [ ] https://github.com/graphql/graphql-js/pull/4096
- [ ] https://github.com/graphql/graphql-js/pull/4081
- [ ] https://github.com/graphql/graphql-js/pull/4017
- [ ] https://github.com/graphql/graphql-js/pull/3915
- [ ] https://github.com/graphql/graphql-js/pull/3617

Coercion/Validation:

- [ ] https://github.com/graphql/graphql-js/pull/4088
- [ ] https://github.com/graphql/graphql-js/pull/4087
- [ ] https://github.com/graphql/graphql-js/pull/3814
- [ ] https://github.com/graphql/graphql-js/pull/3813
- [ ] https://github.com/graphql/graphql-js/pull/3812
- [ ] https://github.com/graphql/graphql-js/pull/3811

Possibly Already Fixed?

- [ ] https://github.com/graphql/graphql-js/pull/3910

Meta-Docs:

- [ ] https://github.com/graphql/graphql-js/pull/4198

**Comment by jasonkuhrt** [comment]
Wonder if we could make the node types not read-only anymore? Wouldn't be a breaking change. Guessing there is a good reason for how it is now, but maybe not?

https://github.com/graphql/graphql-js/discussions/4212

**Comment by benjie** [comment]
Not sure if this is the best place for this, but here are some spec changes that I think we should aim to hit the V17 version; some of them are already merged:

- [x] https://github.com/graphql/graphql-spec/pull/793
- [x] https://github.com/graphql/graphql-spec/pull/1053 / https://github.com/graphql/graphql-js/pull/3986
- [x] https://github.com/graphql/graphql-spec/pull/955 / https://github.com/graphql/graphql-js/issues/3592 / https://github.com/graphql/graphql-js/pull/3601
- [x] https://github.com/graphql/graphql-spec/pull/860 / https://github.com/graphql/graphql-js/pull/3974
- [x] https://github.com/graphql/graphql-spec/pull/891 / argument names are unique; I believe we use arrays to reference them in some places (e.g. `field.args` in `type.toConfig()`?) specifically because Ivan said the spec doesn't require they're unique. Now we do, we should use objects to make these things more ergonomic, like we use objects for fields (keyed by field name). 
- [x] https://github.com/graphql/graphql-spec/pull/976 / I'm not sure if this actually needs anything to change in GraphQL.js TBH.

**Comment by JoviDeCroock** [comment]
> use arrays to reference them in some places

Yes currently we allow for inputs to be done with the `object` syntax but we translate them to arrays in a lot of places. I think mainly to make introspection easier but that's not a great reason, we should change this.

> https://github.com/graphql/graphql-spec/pull/976 / I'm not sure if this actually needs anything to change in GraphQL.js TBH.

Unless this becomes part of the validate/execute phase we don't need any changes here.

**Comment by benjie** [comment]
> Unless this becomes part of the validate/execute phase we don't need any changes here.

That was my initial thought too. Just looking around the codebase, I see `ExecutionResult` has `extensions`:

https://github.com/graphql/graphql-js/blob/6b253e7159a6a6c64c05bcc6bb863fef5a42eeb7/src/execution/execute.ts#L127-L134

Perhaps `GraphQLArgs` should have this too:

https://github.com/graphql/graphql-js/blob/main/src/graphql.ts#L61-L72

And maybe even `ExecutionArgs`:

https://github.com/graphql/graphql-js/blob/6b253e7159a6a6c64c05bcc6bb863fef5a42eeb7/src/execution/execute.ts#L145-L155

This would be a type only change, but I imagine it allows for things like envelop to augment/read from `extensions` which may be useful. Maybe explicitly passing `extensions` from `GraphQLArgs` through to `ExecutionArgs` would be the one concrete (non-type) code change?

**Comment by Speedy1991** [comment]
Are the “Multiple Packages / Bundling” changes really required for v17?

I looked through some of the related issues, and most of them date back to 2024. They also seem primarily focused on improving the bundling experience - which would be great to have. That said, would it make sense to ship the new features (for example, defer) upstream in v17 and move the more invasive bundling improvements to v18 instead?

This could help keep v17 more focused while still allowing the bundling work to mature independently.

**Comment by benjie** [comment]
I'd strongly recommend that we implement a default `maxTokens` value in v17. Allow users to override it, of course, but let's start with something reasonably secure out of the box.

I'm also tempted to say that depth and breadth limits should also be built into the default experience (with the ability to increase or remove them).

**Comment by yaacovCR** [comment]
> and move the more invasive bundling improvements to v18 instead

@Speedy1991

The basic bundling change for v17 is as implemented in https://github.com/graphql/graphql-js/pull/4448 and https://github.com/graphql/graphql-js/pull/4464

We basically have a proper exports map that handles the dual-package hazard for us by intelligently selecting esm when require-esm is available, and otherwise cjs. And we now enable "dev mode" based on the development condition rather than the `NODE_ENV` environment variable or explicitly by calling `enableDevMode()`. Dev mode is not "off" by default, so production builds should just work. Taken altogether, these bundling changes should hopefully not be too invasive!

**Comment by yaacovCR** [comment]
> I'd strongly recommend that we implement a default `maxTokens` value in v17. Allow users to override it, of course, but let's start with something reasonably secure out of the box.
> 
> I'm also tempted to say that depth and breadth limits should also be built into the default experience (with the ability to increase or remove them).

@benjie do you have any working recommendation as to what some sane defaults for these values should be?

**Comment by abishekgiri** [comment]
One more v17 candidate: `execution/values.ts` currently leaks `Object.prototype` members for omitted names like `toString` / `constructor` through `getArgumentValues()` and `getVariableValues()`.

I verified this against plain `16.x.x`: the repro tests from #4653 fail without the behavior change, so the bug is real. However, fixing it cleanly appears to require changing these APIs from returning plain prototype-bearing objects to null-prototype maps, which seems better suited for v17 than as a `16.x.x` backport.

Related:
- #4653
- #4634

**Comment by benjie** [comment]
IMO we should just use `Object.create(null)` wherever we can since `{}` is almost never the right choice.

**Comment by abishekgiri** [comment]
That makes sense to me. After digging through #4653, that was my conclusion too: the clean fix here is really a 17.x.xnull-prototype change, not a16.x.x backport. With #4634 now merged, the rebased #4653 seems to fit that direction well.

**Comment by yaacovCR** [comment]
Closing this as we ready RC state for v17. Golden path work including defaults for `maxTokens` will have to wait until v18 unless we can get a good default value in under the wire, as will max breadth/depth work. batchResolution is a WIP at #4760 but can be released as v17.1
